### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by frazz1234** [Selene-Desna/seln_Outfit_Items#1]
Salut, quesce que source avec le chiffre dnas le serveur ? ESX.RegisterUsableItem('outfit_neon_cyan', function(source) TriggerClientEvent('seln:neon', source,  4) end)

**Comment by poiivre** [comment]
Bonjour, "source" est le joueur auquel mettre la tenue, "4" est la couleur a donner a la tenue pour les tenues ayant plusieurs couleurs sur le même vêtements.

**Comment by frazz1234** [comment]
Excellent, pour les femme, esce que je doit mettre sex a 1 ?? Merci sacrée script... !!! 

Autre quesiton les numéro ne corresponde pas exactement avec les numéro vMenu. Il sont souvent a 1 chiffre prets  comment faire ?? y aller au guess ou ? J'utilise le EUP
