### ISSUE TITLE
Chapeau

### ISSUE THREAD

**Issue by frazz1234** [Selene-Desna/seln_Outfit_Items#2]
Salut! j ai un issue avec les chapeau! je le rentre dans helmet mais rien ne change! comment faire ^ possibilit/ dajouter une animation lors dutilisation et dun freeze time! serait amazing!

thanks

**Comment by frazz1234** [comment]
@poiivre  Une idée ? j'ai aussi découvert quelque chose de wird.. les outfit que tu a déja programmer ont commencer a causer prob avec mon outfit et demande une arme a feux... very strange !

**Comment by poiivre** [comment]
Désolée, je ne suis plus sur FiveM.
Bonne chance dans vos projets.
